services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NS_v4-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:3000" 
    env_file:
      - ./backend/.env
    networks:
      - infra_internal
    environment:
      NODE_ENV: production
      PORT: 3002
    cpus: "1.0"
    mem_limit: 1.5g

networks:
  infra_internal:
    external: true
